### ISSUE TITLE
yazım hatası

### ISSUE THREAD

**Issue by pkryusuf** [HayaliKisi/imla-kurallari-notlarim#1]
3. maddede yazım hatası bulunmaktadır.

**Comment by emreozcan** [comment]
https://github.com/HayaliKisi/imla-kurallari-notlarim/blob/0fe9961ce235720e1215a1e2eb051f8d6d68e1e3/imla-kurallari.md#L8

3. maddede `bildirmek` sözcüğü yanlış olarak `bildimrek` diye yazılmış.
